# -*- coding: utf-8 -*-
"""sueldo_semanal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpcfMPnoyAfhJBwrTkzpMhLs8m0pptV2

calcular sueldo semanal
"""

salario_hora = float(input("ingrese el salario por hora:"))
horas_trabajadas = float(input("ingrese el numero de horas trabajadas:"))

if horas_trabajadas <= 40:
  sueldo_semanal = salario_hora * horas_trabajadas
else:
  horas_extras = horas_trabajadas - 40
  salario_extra = salario_hora * 1.5
  sueldo_semanal = (salario_hora * 40) + (salario_extra * horas_extras)
print(f"el sueldo total semanal es: S/ {sueldo_semanal}")